### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by JBlond** [altzone/phpBorg#1]
The  core_db.php file is missing.

**Comment by altzone** [comment]
Hello, 
thank you for your interest in this little project, the development is far from over yet the system is functional.  I will add the missing file and see to add an English translation.  it also misses a script that I will also add, it allows to add a user on the remote machine so that Borg connects.  I also have to add some dependence on the Web, Bootstrap in particular.  I will soon resume the development of this project and improve the functioning.  Thank you and have a good evening.

Envoyé de mon iPhone

**Comment by JBlond** [comment]
Almost. In line 15 a relative path would be awesome
